<a href="https://colab.research.google.com/github/kshwan95/Machine-Learning/blob/main/%EB%B0%91%EB%B0%94%EB%8B%A5%EB%94%A5%EB%9F%AC%EB%8B%9D2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = 'You say goodbye and I say hello'
text = text.lower()
text = text.replace('.','.')
text

'you say goodbye and i say hello'

In [2]:
words = text.split(' ')
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello']

In [3]:
word_to_id = {}
id_to_word = {}

for word in words:
  if word not in word_to_id:
    new_id = len(word_to_id)
    word_to_id[word] = new_id
    id_to_word[new_id] =word

In [5]:
id_to_word


{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello'}

In [6]:
word_to_id

{'and': 3, 'goodbye': 2, 'hello': 5, 'i': 4, 'say': 1, 'you': 0}

In [7]:
id_to_word[1]

'say'

In [8]:
word_to_id['hello']

5

In [9]:
import numpy as np
corpus = [word_to_id[w]for w in words]
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5])

In [10]:
def preprocess(text):
  text = text.lower()
  text = text.replace('.','.')
  words = text.split(' ')
  word_to_id = {}
  id_to_word = {}

  for word in words:
    if word not in word_to_id:
      new_id = len(word_to_id)
      word_to_id[word] = new_id
      id_to_word[new_id] =word
  corpus = np.array([word_to_id[w]for w in words])

  return corpus, word_to_id, id_to_word

In [11]:
text = 'You say goodbye and I say hello'
corpus, word_to_id,id_to_word = preprocess(text)

In [13]:
import sys
sys.path.append('..')
import numpy as np
text = 'You say goodbye and I say hello'
corpus, word_to_id,id_to_word = preprocess(text)
print(corpus)

[0 1 2 3 4 1 5]


In [14]:
print(id_to_word)

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello'}


In [20]:
def create_co_matrix(corpus, vocab_size, window_size=1):
  corpus_size = len(corpus)
  co_matrix = np.zeros((vocab_size,vocab_size),dtype=np.int32)
  for idx, word_id in enumerate(corpus):
    for i in range(1,window_size+1):
      left_idx = idx - i
      right_idx = idx +i
      if left_idx >=0:
        left_word_id = corpus[left_idx]
        co_matrix[word_id, left_word_id]+=1
      if right_idx < corpus_size:
        right_word_id = corpus[right_idx]
        co_matrix[word_id, right_word_id]+=1
  return co_matrix

In [21]:
def cos_similartiy(x,y,eps=1e-8):
  nx=x/np.sqrt(np.sum(x**2)+eps)
  ny=y/np.sqrt(np.sum(y**2)+eps)
  return np.dot(nx,ny)


In [22]:
text = 'You say goodbye and I say hello'
corpus, word_to_id,id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)
c0 = C[word_to_id['you']]
c1 = C[word_to_id['i']]
print(cos_similartiy(c0,c1))

0.7071067758832467


In [37]:
def most_similar(query, word_to_id, id_to_word, word_matrix, top=5):
  if query not in word_to_id:
    print('%s를 찾을 수 없습니다.'%query)
    return
    print('\n[query]'+query)
    query_id = word_to_id[query]
    query_vec = word_matrix[query_id]

    #코사인 유사도 계산
    vocab_size = len(id_to_word)
    similarity = np.zeros(vocab_size)
    for i in range(vocab_size):
      similarity[i] = cos_similartiy(word_matrix[i],query_vec)
    
    #코사인 유사도를 기준으로 내림차순으로 출력
    count = 0 
    for i in (-1 *similarity).argsort():
      if id_to_word[i] ==query:
        continue
        print('%s: %s'%(id_to_word[i],similarity[i]))

        count +=1
        if count>=top:
          return

In [38]:
x = np.array([100,-20,2])
x.argsort()


array([1, 2, 0])

In [39]:
text = 'You say goodbye and I say hello'
corpus, word_to_id,id_to_word = preprocess(text)
vocab_size = len(word_to_id)
C = create_co_matrix(corpus, vocab_size)

In [40]:
most_similar('you', word_to_id, id_to_word, C, top=5)